### ISSUE TITLE
Alternating the task of Merging into Project master

### ISSUE THREAD

**Issue by benbaka** [AluguntuguiProject/aluguntugui#20]
I am beginning to feel that alternating the merging of pull requests into the project root is becoming a hustle. 

What I am now proposing is that we do it over milestones. So for each milestone only one person has the responsibility of merging changes into master. 

Thoughts ?

**Comment by lcabrini** [comment]
OK, that may be more practical. It seems reasonable to appoint a merge master for each milestone.

Just out of interest, what do you find a hassle thought? I want us to have it for the record, so that we can remind ourselves later why we took certain decisions.

**Comment by benbaka** [comment]
That way, due diligence can be enforced but does not become an impediment to development after every push.

**Comment by benbaka** [comment]
Since we have agreed I am marking the issue as closed. 

@lcabrini Cool ?

**Comment by lcabrini** [comment]
That's fine. You can close.
